development:
  jwt_secret_key: "pp98JsxQ86"
  db_password: nonoyako11

test:
  jwt_secret_key: "pp98JsxQ86"
  db_password: nonoyako11

production:
  jwt_secret_key: "pp98JsxQ86"
  db_password: B8jyKOaD9BW_qBCxI5CkpFHvZzKg_89J
